### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/search-img-tags#11]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/search-img-tags`
3. Go to root directory `cd search-img-tags`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by pradeeps9** [comment]
Hello I would like to work on it.

**Comment by arshadkazmi42** [comment]
@pradeeps9 Sure. go ahead.

**Comment by arshadkazmi42** [comment]
@pradeeps9 Actually I just saw there are already two PRs raised for this. I might have missed it. Sorry about this. This issue is not available anymore

**Comment by arshadkazmi42** [comment]
Fixed in #12
