### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/search-img-tags#4]
- Delete yarn.lock
- Run yarn
- Commit all the changes 
- Create a Pull request

**Comment by imanishbarnwal** [comment]
Is it still open can I do this?

**Comment by arshadkazmi42** [comment]
yes. this is available. go auead

**Comment by imanishbarnwal** [comment]
> yes. this is available. go auead

Yarn command is not working. Command not found

**Comment by arshadkazmi42** [comment]
you can install yarn from here https://classic.yarnpkg.com/en/docs/install/#mac-stable
